### ISSUE TITLE
CI not working (and build failure) [PAXEXAM-928]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.exam2#1009]
**[Amichai Rothman](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:6f99c8d3-db5f-466e-804c-f7aa12bc46e9)** created **[PAXEXAM-928](https://ops4j1.jira.com/browse/PAXEXAM-928)** 

The CI automatic testing on github isn't working, giving a message that the configured version is no longer supported.

Incidentally, the current master build fails with a test error which would have been noticed if the CI was working :smile:

---

Votes: 0, Watches: 1

**Comment by oliverlietz** [comment]
CI with Java 8 is now working with GitHub Actions (again). Build issues will we tackled separately.
