### ISSUE TITLE
Regression - failure when starting two Karaf containers [PAXEXAM-940]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.exam2#1020]
**[Amichai Rothman](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:6f99c8d3-db5f-466e-804c-f7aa12bc46e9)** created **[PAXEXAM-940](https://ops4j1.jira.com/browse/PAXEXAM-940)** 

When upgrading to Pax Exam 4.13.4 with Karaf 4.3.0, an itest that starts two Karaf containers (to test some communication between them) now fails, with the exception below. The same test has been working for years before this. My guess is that commit aa8473a2 caused the regression, where it changed how the free RMI port is detected and didn't account for this scenario.

java.lang.RuntimeException: Problem starting container<br /> at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.start(KarafTestContainer.java:195)<br /> at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.setUp(EagerSingleStagedReactor.java:86)<br /> at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.beforeClass(EagerSingleStagedReactor.java:136)<br /> at org.ops4j.pax.exam.spi.reactors.ReactorManager.beforeClass(ReactorManager.java:457)<br /> at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:97)<br /> at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)<br /> at com.example.itest.setup.TwoContainerPaxExam.run(TwoContainerPaxExam.java:48)<br /> at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)<br /> at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)<br /> at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)<br /> at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)<br /> at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)<br /> at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)<br /> at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)<br /> at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)<br /> Caused by: java.rmi.server.ExportException: internal error: ObjID already in use<br /> at sun.rmi.transport.ObjectTable.putTarget(ObjectTable.java:186)<br /> at sun.rmi.transport.Transport.exportObject(Transport.java:106)<br /> at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:265)<br /> at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:411)<br /> at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)<br /> at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:236)<br /> at sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:213)<br /> at sun.rmi.registry.RegistryImpl.&lt;init&gt;(RegistryImpl.java:198)<br /> at java.rmi.registry.LocateRegistry.createRegistry(LocateRegistry.java:203)<br /> at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.openRegistryOnFreePort(KarafTestContainer.java:228)<br /> at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.start(KarafTestContainer.java:134)<br /> ... 14 more

And this is an additional side effect exception due to stop being called after the start call wasn't successful (perhaps the stop method should be made more robust, to successfully run regardless of how far the start method got):

java.lang.RuntimeException: java.lang.NullPointerException<br /> at com.example.itest.setup.TwoContainerPaxExam.run(TwoContainerPaxExam.java:50)<br /> at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)<br /> at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)<br /> at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)<br /> at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)<br /> at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)<br /> at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)<br /> at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)<br /> at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)<br /> Caused by: java.lang.NullPointerException<br /> at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1423)<br /> at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.stop(KarafTestContainer.java:700)<br /> at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.tearDown(EagerSingleStagedReactor.java:118)<br /> at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.afterClass(EagerSingleStagedReactor.java:132)<br /> at org.ops4j.pax.exam.spi.reactors.ReactorManager.afterClass(ReactorManager.java:441)<br /> at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:107)<br /> at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)<br /> at com.example.itest.setup.TwoContainerPaxExam.run(TwoContainerPaxExam.java:48)<br /> ... 8 more

---

**Affects:** 4.13.4
Votes: 0, Watches: 2

**Comment by amichair** [comment]
Was the option added? How does one use it?

**Comment by b-q** [comment]
> Was the option added? How does one use it?

Hello @amichair  i check the code, the KarafTestContainer class have been modified, before it will choose a free port, from 4.13.4, it will try always with the minimal port, that's the issue.  

For my side,  i did a rollback to 4.13.3. 

So @jbonofre  @ops4j-issues any update about this ?    

Thanks

**Comment by amichair** [comment]
Yeah we're also stuck on 4.13.3 until this is reverted/fixed.

**Comment by amichair** [comment]
Still unusable in 4.13.5.

**Comment by amichair** [comment]
Will this be fixed?

**Comment by oliverlietz** [comment]
@amichair Can you please check with latest snapshot (though no support for range)?

**Comment by amichair** [comment]
The snapshot repository link on the project page in github is broken, where can I find it?

**Comment by amichair** [comment]
btw also the CI link is broken, and the latest version is way behind (on the homepage). Anyhoo, I cloned and built it locally, master branch fails to build, but I tried the 4.x branch and build was successful. Tried 4.13.6-SNAPSHOT with my two container itest and it works well, the issue seems to be resolved!

Still hitting #1093, but that's a different story :-)
