### ISSUE TITLE
documentation links in README.md dangling

### ISSUE THREAD

**Issue by reschke** [ops4j/org.ops4j.pax.exam2#1055]
All of these 404:

http://team.ops4j.org/wiki/display/paxexam4/

http://team.ops4j.org/wiki/display/PAXEXAM4/Documentation

http://team.ops4j.org/browse/PAXEXAM

**Comment by reschke** [comment]
So does...

http://ci.ops4j.org/jenkins/job/org.ops4j.pax.exam-4.x

**Comment by oliverlietz** [comment]
[Current documentation](https://ops4j1.jira.com/wiki/spaces/PAXEXAM4/overview) will move to Git, see #1090.
