### ISSUE TITLE
Release process is not changing version of parent reference on regression project poms  [PAXEXAM-603]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.exam2#313]
**[Cristiano](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:525a5ee9-bc38-4d49-b43c-67926c571c7b)** created **[PAXEXAM-603](https://ops4j1.jira.com/browse/PAXEXAM-603)** 

I cloned the tag exam-reactor-3.4.0 to investigate the regression tests.

But I receive a lot of errors from maven and investigating I found that the parent are using different version than the one pushed.<br /> In the regression tests is:<br /> &lt;parent&gt;<br /> &lt;groupId&gt;org.ops4j.pax&lt;/groupId&gt;<br /> &lt;artifactId&gt;exam&lt;/artifactId&gt;<br /> &lt;version&gt;3.4.0-SNAPSHOt&lt;/version&gt;<br /> &lt;/parent&gt;

but the parent was committed as &lt;version&gt;3.4.0&lt;/version&gt;

---

Votes: 0, Watches: 1

**Comment by oliverlietz** [comment]
Should be fixed.
