### ISSUE TITLE
Add process environment option to Pax Exam [PAXEXAM-804]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.exam2#897]
**[Zoran Regvart](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:0058eb29-f3a5-40ee-894f-a3e398868af8)** created **[PAXEXAM-804](https://ops4j1.jira.com/browse/PAXEXAM-804)** 

When starting the the test container process Pax Exam should provide a way to add a variable to the process environment.<br /> Controlling the application configuration through process environment variables is quite common with the 12+ factor applications, but it might be useful for other cases as well (like setting *_HOME environment variable).

---

Votes: 0, Watches: 1

**Comment by zregvart** [comment]
Implemented in https://github.com/ops4j/org.ops4j.pax.exam2/pull/54
