### ISSUE TITLE
Move from Confluence to Asciidoc [PAXEXAM-906]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.exam2#989]
**[Harald Wellmann](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:22a27d04-788e-4f94-b3c8-ac0f72869ed0)** created **[PAXEXAM-906](https://ops4j1.jira.com/browse/PAXEXAM-906)** 

### []()Goals

* Existing documentation is updated to match the Pax Exam 5 implementation.
* Confluence texts are ported to Asciidoc (manually or with tool support).
* Asciidoc documents are part of the source code repository.
* The documentation is published via GitHub pages for every release.

### []()Benefits

* No more hassle with incompatible Confluence upgrades by Atlassian.
* Users can contribute via pull requests.
* It is easy to publish per-release versions in parallel.

---

Votes: 0, Watches: 1

**Comment by oliverlietz** [comment]
See #1090
